-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.menu_id_menu_seq;
CREATE SEQUENCE IF NOT EXISTS public.metodopago_id_metpag_seq;

CREATE TABLE IF NOT EXISTS public.cargo
(
    id_cargo serial NOT NULL,
    nombre_cargo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    codigo character varying(50) COLLATE pg_catalog."default",
    descripcion character varying(255) COLLATE pg_catalog."default",
    departamento character varying(50) COLLATE pg_catalog."default",
    salario_base numeric(10, 2),
    responsabilidades text COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cargo_pkey PRIMARY KEY (id_cargo),
    CONSTRAINT cargo_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.cash_register_closes
(
    id serial NOT NULL,
    opening_date timestamp without time zone NOT NULL,
    closing_date timestamp without time zone NOT NULL,
    initial_amount numeric(10, 2) NOT NULL DEFAULT 0.00,
    final_amount numeric(10, 2) NOT NULL DEFAULT 0.00,
    expected_amount numeric(10, 2) DEFAULT 0.00,
    difference numeric(10, 2) DEFAULT 0.00,
    total_sales numeric(10, 2) DEFAULT 0.00,
    total_transactions integer DEFAULT 0,
    cash_amount numeric(10, 2) DEFAULT 0.00,
    card_amount numeric(10, 2) DEFAULT 0.00,
    other_amount numeric(10, 2) DEFAULT 0.00,
    closed_by character varying(100) COLLATE pg_catalog."default",
    notes character varying(1000) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cash_register_closes_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.cash_register_closes
    IS 'Tabla para registrar los cierres de caja diarios';

COMMENT ON COLUMN public.cash_register_closes.opening_date
    IS 'Fecha y hora de apertura de caja';

COMMENT ON COLUMN public.cash_register_closes.closing_date
    IS 'Fecha y hora de cierre de caja';

COMMENT ON COLUMN public.cash_register_closes.initial_amount
    IS 'Monto inicial en caja al abrir';

COMMENT ON COLUMN public.cash_register_closes.final_amount
    IS 'Monto final en caja al cerrar';

COMMENT ON COLUMN public.cash_register_closes.expected_amount
    IS 'Monto esperado según ventas y gastos';

COMMENT ON COLUMN public.cash_register_closes.difference
    IS 'Diferencia entre monto final y esperado';

COMMENT ON COLUMN public.cash_register_closes.total_sales
    IS 'Total de ventas del periodo';

COMMENT ON COLUMN public.cash_register_closes.total_transactions
    IS 'Número total de transacciones';

COMMENT ON COLUMN public.cash_register_closes.cash_amount
    IS 'Monto en efectivo';

COMMENT ON COLUMN public.cash_register_closes.card_amount
    IS 'Monto en tarjeta';

COMMENT ON COLUMN public.cash_register_closes.other_amount
    IS 'Monto en otros métodos de pago';

COMMENT ON COLUMN public.cash_register_closes.closed_by
    IS 'Usuario que realizó el cierre';

COMMENT ON COLUMN public.cash_register_closes.notes
    IS 'Notas o comentarios adicionales';

CREATE TABLE IF NOT EXISTS public.categoria
(
    id_categoria serial NOT NULL,
    nombre_categoria character varying(30) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(30) COLLATE pg_catalog."default",
    orden_visualizacion integer DEFAULT 0,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Categoria_pkey" PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente serial NOT NULL,
    nombre_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    apellido_cliente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    telefono_cliente character varying(10) COLLATE pg_catalog."default" NOT NULL,
    direccion_cliente character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    numero_identificacion character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.delivery
(
    id_delivery serial NOT NULL,
    id_pedido integer NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT delivery_pkey PRIMARY KEY (id_delivery)
);

COMMENT ON TABLE public.delivery
    IS 'Tabla de domicilios para pedidos tipo DOMICILIO';

COMMENT ON COLUMN public.delivery.estado
    IS 'Estados: PENDING, PREPARING, IN_TRANSIT, DELIVERED, CANCELLED';

CREATE TABLE IF NOT EXISTS public."detallePedido"
(
    id_pedido integer NOT NULL,
    id_menu integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario real NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.empleado
(
    id_empleado serial NOT NULL,
    id_cargo integer NOT NULL,
    nom_empleado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ape_empleado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tel_empleado character varying(10) COLLATE pg_catalog."default" NOT NULL,
    direccion_empleado character varying(30) COLLATE pg_catalog."default" NOT NULL,
    correo_empleado character varying(30) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    numero_documento character varying(20) COLLATE pg_catalog."default",
    fecha_contratacion date DEFAULT CURRENT_DATE,
    salario numeric(10, 2),
    notas text COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Empleado_pkey" PRIMARY KEY (id_empleado),
    CONSTRAINT empleado_numero_documento_key UNIQUE (numero_documento)
);

CREATE TABLE IF NOT EXISTS public."menú"
(
    id_menu integer NOT NULL DEFAULT nextval('menu_id_menu_seq'::regclass),
    nombre_menu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    precio real NOT NULL,
    id_categoria integer NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'A'::character varying,
    CONSTRAINT "Menú_pkey" PRIMARY KEY (id_menu)
);

CREATE TABLE IF NOT EXISTS public.mesa
(
    id_mesa serial NOT NULL,
    numero_mesa integer NOT NULL,
    capacidad integer NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    ubicacion character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT "Mesa_pkey" PRIMARY KEY (id_mesa)
);

CREATE TABLE IF NOT EXISTS public."metodoPago"
(
    "id_metPag" integer NOT NULL DEFAULT nextval('metodopago_id_metpag_seq'::regclass),
    "nombre_metPag" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "metodoPago_pkey" PRIMARY KEY ("id_metPag")
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial NOT NULL,
    "Id_pedido" integer NOT NULL,
    "id_metPag" integer NOT NULL,
    monto real NOT NULL,
    valor_domiciliario real NOT NULL DEFAULT 0,
    fecha_pago date NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pago_pkey PRIMARY KEY (id_pago)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id_pedido serial NOT NULL,
    id_cliente integer NOT NULL,
    id_usuario integer NOT NULL,
    "valor a pagar" real NOT NULL,
    id_mesa integer,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    tipo_pedido character varying(20) COLLATE pg_catalog."default" DEFAULT 'ESTABLECIMIENTO'::character varying,
    notas text COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "Pedido_pkey" PRIMARY KEY (id_pedido)
);

COMMENT ON COLUMN public.pedido.tipo_pedido
    IS 'Tipo de pedido: ESTABLECIMIENTO o DOMICILIO';

COMMENT ON COLUMN public.pedido.notas
    IS 'Notas adicionales del pedido ingresadas por el mesero';

CREATE TABLE IF NOT EXISTS public.permissions
(
    id serial NOT NULL,
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    module character varying(50) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.profile_permissions
(
    profile_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT profile_permissions_pkey PRIMARY KEY (profile_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.rol
(
    id_rol serial NOT NULL,
    nombre_rol character varying(12) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Rol_pkey" PRIMARY KEY (id_rol)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario serial NOT NULL,
    id_empleado integer NOT NULL,
    username character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha_registro date NOT NULL,
    id_rol integer NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.delivery
    ADD CONSTRAINT fk_delivery_pedido FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_delivery_pedido
    ON public.delivery(id_pedido);


ALTER TABLE IF EXISTS public."detallePedido"
    ADD CONSTRAINT fk_detalle_menu FOREIGN KEY (id_menu)
    REFERENCES public."menú" (id_menu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."detallePedido"
    ADD CONSTRAINT fk_detalle_pedido FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.empleado
    ADD CONSTRAINT fk_cargo FOREIGN KEY (id_cargo)
    REFERENCES public.cargo (id_cargo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_empleado_cargo
    ON public.empleado(id_cargo);


ALTER TABLE IF EXISTS public."menú"
    ADD CONSTRAINT fk_categoria FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT fk_pago_metodo FOREIGN KEY ("id_metPag")
    REFERENCES public."metodoPago" ("id_metPag") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT fk_pago_pedido FOREIGN KEY ("Id_pedido")
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT fk_pedido_mesa FOREIGN KEY (id_mesa)
    REFERENCES public.mesa (id_mesa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT fk_pedido_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.profile_permissions
    ADD CONSTRAINT profile_permissions_permission_id_fkey FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.profile_permissions
    ADD CONSTRAINT profile_permissions_profile_id_fkey FOREIGN KEY (profile_id)
    REFERENCES public.rol (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT fk_empleado FOREIGN KEY (id_empleado)
    REFERENCES public.empleado (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT fk_rol FOREIGN KEY (id_rol)
    REFERENCES public.rol (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


-- ============================================
-- MIGRATION 2026-06-03: timestamps en pedido
-- Descripción: agrega fecha_creacion y fecha_actualizacion a la tabla pedido
-- Aplicar contra terraza_pruebas_mayo (BD actual)
-- Idempotente: usa ADD COLUMN IF NOT EXISTS, se puede correr múltiples veces
-- ============================================

ALTER TABLE public.pedido
    ADD COLUMN IF NOT EXISTS fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE public.pedido
    ADD COLUMN IF NOT EXISTS fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL;


END;