# ====== APP ======
server.port=${SERVER_PORT:8081}
spring.application.name=bombonera-pos

# ====== DATASOURCE ======
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bombonera}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:6509}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# ====== JPA / Hibernate ======
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ====== JWT ======
app.jwt.secret=${APP_JWT_SECRET:aK3oAY2TT19SWAA2AWcr/fmAM+nryT3P40/vXntDVmo=}
app.jwt.expiration=86400000

# ====== Jackson (v3) — dates as ISO strings by default ======

# ====== Logging ======
logging.level.com.bombonera=${LOG_LEVEL:DEBUG}
